### ISSUE TITLE
i18n.setLocale not saving

### ISSUE THREAD

**Issue by michael-trinity** [vazco/meteor-universe-i18n#115]
Using Meteor 1.8.1

Any different React component I have to do `i18n.setLocale()` again as the locale resets to en-US.

Is there a way to set the locale once in the complete App?

**Comment by cristo-rabani** [comment]
Hello @michael-trinity , 
This is the correct behavior of `18n.setLocale()` because this method sets proper locale for current runtime, in other words, it does not use any persistent storage because projects need are different.
e.g. a value of this setting can be saved in local storage, session storage, by cookies, as a part of URL and so on.

So, Your implementation should decide where to store this value, how long, for who and all other policy.
