### ISSUE TITLE
Lots of calls to universe.i18n.setServerLocaleForConnection

### ISSUE THREAD

**Issue by brianlukoff** [vazco/meteor-universe-i18n#127]
In production (I have not been able to replicate locally) there will sometimes be tons of calls to `universe.i18n.setServerLocaleForConnection` for a while, and then the volume will die down to a normal level. (`i18n.setLocale` is being called in `Meteor.startup` and in response to user requests to change language, but not otherwise.) Has anyone else seen similar behavior?

**Comment by radekmie** [comment]
Hi @brianlukoff. As I checked, I can confirm it happens in our apps as well. If you'll find anything suspicious, please do let us know. We'll try to look into it shortly.

**Comment by radekmie** [comment]
@brianlukoff: could you check how often `Meteor.connection._stream.on('reset', () => console.log('reset'))` fires in your app? I suspect [this](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/client/api.js#L68-L72) code to be responsible for that (the other call is in `setLocale`). I've tried to reproduce it once again in one of our apps today and was not able to.

Also, I thought about adding `this.unblock()` in this method or even an option to make it possible. In your app, the problem is that it's called so often or that it's somewhere high in your APM? If the former, maybe try this:

```ts
const originalSetLocale = i18n.setLocale;
i18n.setLocale = (locale, options) =>
  i18n.getLocale() === i18n.normalize(locale)
    ? Promise.resolve()
    : originalSetLocale.call(i18n, locale, options);
```

**Comment by brianlukoff** [comment]
Good idea -- I think that's probably it. The issue is that it's being called too frequently -- but it happens in spikes. Will give that a try!

**Comment by radekmie** [comment]
Then do let me know, whether it worked. I'm working on something in this regard, but it'd be good to know, whether this workaround works.

**Comment by brianlukoff** [comment]
An update on this -- I don't think we have seen a recurrence of this issue after using your workaround!

**Comment by radekmie** [comment]
We've decided to implement a config option for this workaround. For now it'll be off by default, but it may change in the next major version.

**Comment by evolross** [comment]
We ran into this too. A couple thoughts on the above:
- Is perhaps an implementation change in order if the existing implementation of `sameLocaleOnServerConnection` results in hundreds of thousands of extra calls? Since `ignoreNoopLocaleChanges` is undocumented and defaults to `false` and `sameLocaleOnServerConnection` defaults `true`, this should be affecting everyone.
- I'll do a documentation update PR to explain `ignoreNoopLocaleChanges` and how it affects `sameLocaleOnServerConnection`, as it should be mentioned.

However, I'm not totally on what `sameLocaleOnServerConnection` does. It keeps the server in sync with the locale selected on the client?

**Comment by evolross** [comment]
Some thoughts on `ignoreNoopLocaleChanges`. Ideally, our implementation looks something like this on load:

1. Get a `locale` from a stored setting in our app (not the default browser) and call `setLocale()`
2. In `onChangeLocale()` dynamically synchronously import the translation file (e.g. `app.en.i18n.json`)
3. Once loaded, set a reactive var that controls rendering the route in the app

Without `ignoreNoopLocaleChanges` everything works fine. But we have literally hundreds of thousands of extra calls to `universe.i18n.setServerLocaleForConnection`.

Adding `ignoreNoopLocaleChanges` broke this process. As the above step 1 will not fire if the `getLocale()` mysteriously initiated in the browser at startup is the _same_ as the `locale` setting from the app. Not firing step 1 breaks everything as no dynamic language file ever gets loaded and the route never renders.

It's not really mentioned in the docs what `locale` gets set and returned by `getLocale()` before adding any locales to it yourself.

Since `onChangeLocale()` won't fire if the two locales are the same, our work-around was to extend `setLocale()` forcing it to always run our callback logic from `onChangeLocale()` and then having it call `originalSetLocale()`. If `ignoreNoopLocaleChanges` causes the the update and callback not to fire, it's fine, we still run our dynamic loading logic.
