### ISSUE TITLE
[1.32.3] Warning: Max Listeners Exceeded

### ISSUE THREAD

**Issue by jamalcoder** [vazco/meteor-universe-i18n#139]
Meteor version : 2.2.4

after updating the package from 1.31.0 to 1.32.3 i got this warning.

![Capture](https://user-images.githubusercontent.com/11628272/139326088-79b0bbd2-c1d4-472d-abed-7726bddc9573.PNG)

**Comment by piotrpospiech** [comment]
@jamalcoder, @izaa, React component adds his listener to detect a language change, so the number of listeners depends on how many `T` components will be rendered on a page. 

It is the expected behavior of how this system works. There is no way to reduce the number of listeners. We can change the number of max listeners, but it really depends on the project, so I suggest to set `defaultMaxListeners` on your own.

**Comment by jamalcoder** [comment]
hi @piotrpospiech , can you explain why we don't have this issue in previous versions like 1.31.0.

**Comment by radekmie** [comment]
@jamalcoder Can you confirm that this was the only package you've updated? I've checked the code and there are no differences with regards to the React integration.

**Comment by jamalcoder** [comment]
@radekmie yes it's the only package i have update

**Comment by piotrpospiech** [comment]
@radekmie I rechecked this issue. It actually only appears since `v1.32.0`. Previously we used custom implemented `Emitter` and now we're using `EventEmitter`. We haven't implemented listeners limit.

**Comment by jamalcoder** [comment]
i resolve the issue like that  i18n._events.setMaxListeners(15);
if there is a better way please suggest it.

**Comment by bladerunner2020** [comment]
> i resolve the issue like that i18n._events.setMaxListeners(15);
> if there is a better way please suggest it.

Thank you a lot. In my case the number of T elements on page is higher 50... ))
