### ISSUE TITLE
An example using files

### ISSUE THREAD

**Issue by Unforgiven-wanda** [vazco/meteor-universe-i18n#26]
Hello,
I'm trying to use files to store my translations, but however much I read the docs they remain hopelessly obscure to me. while "i18n.addTranslation" works, adding my translations to a YAML file does not for whatever reason. A live-example would be most welcome as searching for one turned up nothing.

Thank you.

**Comment by cristo-rabani** [comment]
Hello,
This can be probably because of:

- Your translations files are not stored in common space

- Translation files should be named `[locale].i18n.yml` e.g. `fr-fr.i18n.yml`

- You are using locale that isn't bundled for clent,  as a default only `en-US` are bundled for the client.

So, if you use diffrent locale as a first locale or you want some locale/s to be attached in client bundle you must set env variable for bundling (building) proccess with locales that you want to have or 'all' to have attached all locales in client bundle

If your locales are in package as a default they are namespaced of package name. To have them without package namespace please add to them `_namespace: ''` as a first line of your yml file.

**Comment by Unforgiven-wanda** [comment]
Indeed. I've solved this issue some time ago and this was exactly it.
Thank you.
